---
jiraDomains:

  default:
    user: "email@yourjira.com"
    password: "aTotallyRealToken"
    url: "https://myjira.atlassian.net"
    query: 'project = "Project" AND status = Done'
    fields: 
      - "id"
      - "fields/worklog/worklogs/*/timeSpent"
      - "fields/worklog/worklogs/*/author/emailAddress"
      - "fields/worklog/worklogs/*/author/displayName"

  secondProfile:
    user: "email@yourjira.com"
    password: "aTotallyRealToken"
    url: "https://myjira.atlassian.net"
    query: 'project = "Project" AND status = Done'
    fields: 
      - "id"
      - "fields/worklog/worklogs/*/timeSpent"
      - "fields/worklog/worklogs/*/author/emailAddress"
      - "fields/worklog/worklogs/*/author/displayName"

config:
  output: "output/"
...